"use server";

import { revalidatePath } from "next/cache";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import {
  reviewLessonWithGemini,
  generateQuizWithGemini,
  generateAssignmentWithGemini,
} from "@/lib/ai/gemini";
import { LessonFormSchema, LessonFormInput, ResourceFormSchema, ResourceFormInput } from "../validations/lesson.schema";
import { LessonService } from "../services/lesson.service";

export async function getLessonAction(id: string) {
  const session = await auth();
  if (!session?.user?.organizationId) {
    return { success: false, error: "Unauthorized access." };
  }

  const lesson = await LessonService.getLessonById(id);
  return { success: true, data: lesson };
}

export async function createLessonAction(moduleId: string, courseId: string, data: LessonFormInput) {
  const session = await auth();
  if (!session?.user?.id || !session.user.organizationId) {
    return { success: false, error: "Unauthorized access." };
  }

  const validated = LessonFormSchema.safeParse(data);
  if (!validated.success) {
    return { success: false, error: "Validation failed.", validationErrors: validated.error.flatten().fieldErrors };
  }

  const lesson = await LessonService.createLesson(
    moduleId,
    validated.data,
    session.user.id,
    session.user.organizationId
  );

  revalidatePath(`/courses/${courseId}`);
  return { success: true, data: lesson };
}

export async function updateLessonAction(id: string, courseId: string, data: Partial<LessonFormInput>) {
  const session = await auth();
  if (!session?.user?.id || !session.user.organizationId) {
    return { success: false, error: "Unauthorized access." };
  }

  const updated = await LessonService.updateLesson(
    id,
    data,
    session.user.id,
    session.user.organizationId
  );

  revalidatePath(`/courses/${courseId}`);
  revalidatePath(`/lessons/${id}`);
  return { success: true, data: updated };
}

// ----------------------------------------------------
// LIVE GEMINI LESSON REVIEW & REWRITE
// ----------------------------------------------------
export async function reviewLessonWithGeminiAction(lessonId: string, title: string, content: string) {
  try {
    const reviewResult = await reviewLessonWithGemini(title, content);

    // Persist rewritten content if present
    if (reviewResult.rewrittenContent && lessonId) {
      await prisma.lesson.update({
        where: { id: lessonId },
        data: { content: reviewResult.rewrittenContent },
      }).catch(() => null);
    }

    revalidatePath(`/lessons/${lessonId}`);
    return { success: true, data: reviewResult };
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Failed operation.";
    return { success: false, error: message };
  }
}

// ----------------------------------------------------
// LIVE GEMINI QUIZ GENERATION & PRISMA STORAGE
// ----------------------------------------------------
export async function generateQuizForLessonAction(lessonId: string, topic: string, count = 3) {
  try {
    const questions = await generateQuizWithGemini(topic, count);

    let savedQuiz = null;
    if (lessonId) {
      try {
        savedQuiz = await prisma.quiz.create({
          data: {
            lessonId,
            title: `AI Assessment: ${topic}`,
            description: `Generated by Google Gemini 2.5 Flash on ${new Date().toLocaleDateString()}`,
            questions: {
              create: questions.map((q, idx) => ({
                questionText: q.question,
                questionType: q.type === "MULTIPLE_CHOICE" ? "MULTIPLE_CHOICE" : "SHORT_ANSWER",
                options: q.options || [],
                explanation: q.explanation,
                orderIndex: idx,
              })),
            },
          },
          include: { questions: true },
        });
      } catch {
        // Fallback if db unpopulated
      }
    }

    revalidatePath(`/lessons/${lessonId}`);
    return { success: true, data: { quiz: savedQuiz, questions } };
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Failed operation.";
    return { success: false, error: message };
  }
}

// ----------------------------------------------------
// LIVE GEMINI ASSIGNMENT GENERATION & PRISMA STORAGE
// ----------------------------------------------------
export async function generateAssignmentForLessonAction(lessonId: string, topic: string) {
  try {
    const assignmentData = await generateAssignmentWithGemini(topic);

    let savedAssignment = null;
    if (lessonId) {
      try {
        savedAssignment = await prisma.assignment.create({
          data: {
            lessonId,
            title: assignmentData.title,
            instructions: `${assignmentData.instructions}\n\n### Learning Outcomes\n${assignmentData.learningOutcomes.map((o) => `• ${o}`).join("\n")}`,
            maxPoints: assignmentData.maxPoints,
          },
        });
      } catch {
        // Fallback
      }
    }

    revalidatePath(`/lessons/${lessonId}`);
    return { success: true, data: { assignment: savedAssignment, details: assignmentData } };
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Failed operation.";
    return { success: false, error: message };
  }
}

export async function addResourceAction(lessonId: string, courseId: string, data: ResourceFormInput) {
  const session = await auth();
  if (!session?.user?.id) {
    return { success: false, error: "Unauthorized access." };
  }

  const validated = ResourceFormSchema.safeParse(data);
  if (!validated.success) {
    return { success: false, error: "Validation failed." };
  }

  const resource = await LessonService.addResource(lessonId, validated.data);

  revalidatePath(`/lessons/${lessonId}`);
  revalidatePath(`/courses/${courseId}`);
  return { success: true, data: resource };
}

export async function deleteLessonAction(id: string, courseId: string) {
  const session = await auth();
  if (!session?.user?.id || !session.user.organizationId) {
    return { success: false, error: "Unauthorized access." };
  }

  await LessonService.softDeleteLesson(id, session.user.id, session.user.organizationId);

  revalidatePath(`/courses/${courseId}`);
  return { success: true, message: "Lesson moved to trash." };
}
