"use client";

import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Sparkles,
  Zap,
  AlertTriangle,
  TrendingUp,
  CheckCircle2,
  Bot,
  ShieldCheck,
  RefreshCw,
  GitMerge,
  Award,
  Activity,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/components/ui/toast";

interface LiveActivity {
  id: string;
  type: "review" | "embedding" | "duplicate" | "graph" | "score" | "assignment";
  message: string;
  progress?: number;
  status: "in_progress" | "completed";
  timestamp: string;
}

export function LivingAIWorkspace() {
  const { toast } = useToast();
  const [duplicateMerged, setDuplicateMerged] = useState(false);
  const [coursesUpgraded, setCoursesUpgraded] = useState(false);

  // Live Activity Feed State
  const [activities, setActivities] = useState<LiveActivity[]>([
    {
      id: "act-1",
      type: "review",
      message: 'AI Reviewing Course "Advanced React 19 & Next.js 16 Enterprise Architecture"',
      progress: 89,
      status: "in_progress",
      timestamp: "Just now",
    },
    {
      id: "act-2",
      type: "embedding",
      message: "Generating 1538D pgvector Embeddings for Module 3: State Engines",
      status: "completed",
      timestamp: "2s ago",
    },
    {
      id: "act-3",
      type: "duplicate",
      message: "Detecting Duplicate Lessons across 14 active catalog modules",
      status: "completed",
      timestamp: "5s ago",
    },
    {
      id: "act-4",
      type: "graph",
      message: "Building Knowledge Graph for Distributed AI Infrastructure",
      progress: 65,
      status: "in_progress",
      timestamp: "8s ago",
    },
    {
      id: "act-5",
      type: "score",
      message: "Recalculating Organization Catalog Health Score: 96.8 / 100",
      status: "completed",
      timestamp: "12s ago",
    },
  ]);

  // Simulate real-time continuous AI background activity streams
  useEffect(() => {
    const streamTemplates: { type: LiveActivity["type"]; message: string }[] = [
      { type: "review", message: 'AI Audit: Evaluating Bloom\'s Taxonomy coverage for "System Design"' },
      { type: "embedding", message: "Updating pgvector HNSW index for 24 lesson content nodes" },
      { type: "duplicate", message: "Semantic Scan: 0 new duplicate overlaps detected in Module 5" },
      { type: "assignment", message: "Reviewer Dr. Aris Thorne assigned to 'Distributed Systems'" },
      { type: "score", message: "WCAG 2.1 Accessibility Audit passed for all 18 published courses" },
    ];

    const interval = setInterval(() => {
      const template = streamTemplates[Math.floor(Math.random() * streamTemplates.length)];
      const newAct: LiveActivity = {
        id: `act-${Date.now()}`,
        type: template.type,
        message: template.message,
        status: Math.random() > 0.4 ? "completed" : "in_progress",
        progress: Math.floor(Math.random() * 40) + 50,
        timestamp: "Just now",
      };

      setActivities((prev) => [newAct, ...prev.slice(0, 5)]);
    }, 4500);

    return () => clearInterval(interval);
  }, []);

  const handleMergeDuplicates = () => {
    setDuplicateMerged(true);
    toast({
      type: "success",
      title: "AI Duplicate Merge Complete",
      description: "Merged Lesson 2.1 into Module 4. 0 duplicates remaining.",
    });
  };

  const handleUpgradeCourses = () => {
    setCoursesUpgraded(true);
    toast({
      type: "success",
      title: "React 19 AI Upgrade Triggered",
      description: "Converted legacy hooks to React Server Components & Server Actions.",
    });
  };

  return (
    <div className="space-y-8">
      {/* 1. TODAY'S LIVE AI INSIGHTS SECTION */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-purple-500/10 text-purple-400 border border-purple-500/20">
              <Zap className="h-4 w-4" />
            </div>
            <h2 className="text-lg font-bold text-foreground flex items-center gap-2">
              Today&apos;s Live AI Insights
              <span className="rounded-full bg-emerald-500/10 border border-emerald-500/20 px-2 py-0.5 text-[10px] font-mono text-emerald-400 flex items-center gap-1">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-400 animate-pulse" /> Live Telemetry
              </span>
            </h2>
          </div>
          <span className="text-xs text-muted-foreground hidden sm:inline">
            Automated recommendations generated by Gemini 2.0 & GPT-4o
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {/* Card 1: Duplicate Lessons */}
          <motion.div
            whileHover={{ y: -4 }}
            className={`rounded-xl border p-4 backdrop-blur-md transition-all ${
              duplicateMerged
                ? "border-emerald-500/30 bg-emerald-500/5"
                : "border-amber-500/30 bg-amber-500/5 shadow-lg shadow-amber-500/5"
            }`}
          >
            <div className="flex items-start justify-between">
              <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-amber-500/10 text-amber-400 border border-amber-500/20">
                <GitMerge className="h-4.5 w-4.5" />
              </div>
              <span className="rounded-full bg-amber-500/10 px-2 py-0.5 text-[10px] font-mono text-amber-400 border border-amber-500/20">
                {duplicateMerged ? "Resolved" : "Action Needed"}
              </span>
            </div>
            <div className="mt-3 space-y-1">
              <h4 className="text-xs font-bold text-foreground">
                {duplicateMerged ? "0 Duplicates Found" : "3 Duplicate Lessons Flagged"}
              </h4>
              <p className="text-[11px] text-muted-foreground leading-relaxed">
                {duplicateMerged
                  ? "All duplicate lessons consolidated into shared prerequisite modules."
                  : "98.4% match detected between Lesson 2.1 & Lesson 4.2 in System Design."}
              </p>
            </div>
            <div className="mt-4 pt-3 border-t border-border/50">
              {!duplicateMerged ? (
                <Button
                  size="sm"
                  variant="outline"
                  onClick={handleMergeDuplicates}
                  className="w-full text-xs border-amber-500/30 text-amber-400 hover:bg-amber-500/10"
                >
                  <Sparkles className="h-3 w-3 mr-1.5" /> Run AI Auto-Merge
                </Button>
              ) : (
                <span className="flex items-center gap-1 text-[11px] text-emerald-400 font-semibold">
                  <CheckCircle2 className="h-3.5 w-3.5" /> Overlaps Merged
                </span>
              )}
            </div>
          </motion.div>

          {/* Card 2: Outdated React Courses */}
          <motion.div
            whileHover={{ y: -4 }}
            className={`rounded-xl border p-4 backdrop-blur-md transition-all ${
              coursesUpgraded
                ? "border-emerald-500/30 bg-emerald-500/5"
                : "border-purple-500/30 bg-purple-500/5 shadow-lg shadow-purple-500/5"
            }`}
          >
            <div className="flex items-start justify-between">
              <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-purple-500/10 text-purple-400 border border-purple-500/20">
                <AlertTriangle className="h-4.5 w-4.5" />
              </div>
              <span className="rounded-full bg-purple-500/10 px-2 py-0.5 text-[10px] font-mono text-purple-400 border border-purple-500/20">
                {coursesUpgraded ? "Upgraded" : "2 Courses"}
              </span>
            </div>
            <div className="mt-3 space-y-1">
              <h4 className="text-xs font-bold text-foreground">
                {coursesUpgraded ? "All Courses Up-to-Date" : "2 Outdated React Courses"}
              </h4>
              <p className="text-[11px] text-muted-foreground leading-relaxed">
                {coursesUpgraded
                  ? "Updated legacy hooks to React 19 Server Components and Server Actions."
                  : "Legacy React 18 patterns detected in 2 catalog modules."}
              </p>
            </div>
            <div className="mt-4 pt-3 border-t border-border/50">
              {!coursesUpgraded ? (
                <Button
                  size="sm"
                  variant="outline"
                  onClick={handleUpgradeCourses}
                  className="w-full text-xs border-purple-500/30 text-purple-400 hover:bg-purple-500/10"
                >
                  <Bot className="h-3 w-3 mr-1.5" /> Upgrade via Gemini AI
                </Button>
              ) : (
                <span className="flex items-center gap-1 text-[11px] text-emerald-400 font-semibold">
                  <CheckCircle2 className="h-3.5 w-3.5" /> Upgraded to React 19
                </span>
              )}
            </div>
          </motion.div>

          {/* Card 3: Quality Improvement */}
          <motion.div
            whileHover={{ y: -4 }}
            className="rounded-xl border border-emerald-500/30 bg-emerald-500/5 p-4 backdrop-blur-md shadow-lg shadow-emerald-500/5"
          >
            <div className="flex items-start justify-between">
              <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                <TrendingUp className="h-4.5 w-4.5" />
              </div>
              <span className="rounded-full bg-emerald-500/10 px-2 py-0.5 text-[10px] font-mono text-emerald-400 border border-emerald-500/20">
                +7.4% This Week
              </span>
            </div>
            <div className="mt-3 space-y-1">
              <h4 className="text-xs font-bold text-foreground">Catalog Quality Improved</h4>
              <p className="text-[11px] text-muted-foreground leading-relaxed">
                Bloom&apos;s Taxonomy coverage increased from 82% to 89.4% across active modules.
              </p>
            </div>
            <div className="mt-4 pt-3 border-t border-border/50 flex items-center justify-between text-[11px] text-emerald-400 font-semibold">
              <span className="flex items-center gap-1">
                <CheckCircle2 className="h-3.5 w-3.5" /> Verified by GPT-4o
              </span>
              <span className="font-mono">96.8 / 100</span>
            </div>
          </motion.div>

          {/* Card 4: Top Productive Author */}
          <motion.div
            whileHover={{ y: -4 }}
            className="rounded-xl border border-blue-500/30 bg-blue-500/5 p-4 backdrop-blur-md shadow-lg shadow-blue-500/5"
          >
            <div className="flex items-start justify-between">
              <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-blue-500/10 text-blue-400 border border-blue-500/20">
                <Award className="h-4.5 w-4.5" />
              </div>
              <span className="rounded-full bg-blue-500/10 px-2 py-0.5 text-[10px] font-mono text-cyan-400 border border-blue-500/20">
                Top Author
              </span>
            </div>
            <div className="mt-3 space-y-1">
              <h4 className="text-xs font-bold text-foreground flex items-center gap-1">
                Shivam Kumar
              </h4>
              <p className="text-[11px] text-muted-foreground leading-relaxed">
                4 Published Courses • 98.2% Avg Quality Score • 0 Reviewer Rejections
              </p>
            </div>
            <div className="mt-4 pt-3 border-t border-border/50 flex items-center justify-between text-[11px] text-cyan-400 font-semibold">
              <span className="flex items-center gap-1">
                <ShieldCheck className="h-3.5 w-3.5" /> Lead Architect
              </span>
              <span className="font-mono">Rank #1</span>
            </div>
          </motion.div>
        </div>
      </div>

      {/* 2. REAL-TIME AI ACTIVITY STREAM TICKER */}
      <div className="rounded-2xl border border-border bg-card p-5 shadow-xl space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-border/60 pb-3">
          <div className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-cyan-500/10 text-cyan-400 border border-cyan-500/20">
              <Activity className="h-4 w-4" />
            </div>
            <h3 className="text-sm font-bold text-foreground flex items-center gap-2">
              Real-Time AI Activity Stream
              <span className="flex h-2 w-2 rounded-full bg-cyan-400 animate-ping" />
            </h3>
          </div>
          <span className="text-[11px] text-muted-foreground font-mono">
            Streaming 1538D vector embeddings & automated audits
          </span>
        </div>

        <div className="space-y-2.5">
          <AnimatePresence initial={false}>
            {activities.map((act) => (
              <motion.div
                key={act.id}
                initial={{ opacity: 0, y: -10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, height: 0 }}
                transition={{ duration: 0.25 }}
                className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 rounded-xl border border-border/50 bg-muted/30 p-3 text-xs"
              >
                <div className="flex items-center gap-3 min-w-0">
                  {act.status === "in_progress" ? (
                    <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-cyan-500/20 text-cyan-400 border border-cyan-500/30">
                      <RefreshCw className="h-3 w-3 animate-spin" />
                    </div>
                  ) : (
                    <div className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-emerald-500/20 text-emerald-400 border border-emerald-500/30">
                      <CheckCircle2 className="h-3 w-3" />
                    </div>
                  )}

                  <div className="min-w-0">
                    <p className="font-medium text-foreground truncate">{act.message}</p>
                    <span className="text-[10px] text-muted-foreground font-mono">{act.timestamp}</span>
                  </div>
                </div>

                {/* Progress Bar for in-progress activities */}
                {act.status === "in_progress" && act.progress !== undefined && (
                  <div className="flex items-center gap-2 sm:w-36 shrink-0">
                    <div className="h-1.5 flex-1 overflow-hidden rounded-full bg-muted">
                      <div
                        className="h-full bg-gradient-to-r from-cyan-500 to-indigo-500 transition-all duration-300"
                        style={{ width: `${act.progress}%` }}
                      />
                    </div>
                    <span className="text-[10px] font-mono text-cyan-400">{act.progress}%</span>
                  </div>
                )}

                {act.status === "completed" && (
                  <span className="rounded-full bg-emerald-500/10 border border-emerald-500/20 px-2 py-0.5 text-[10px] font-mono text-emerald-400 shrink-0">
                    Completed
                  </span>
                )}
              </motion.div>
            ))}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}
